### ISSUE TITLE
Segfault?

### ISSUE THREAD

**Issue by matiasinsaurralde** [OWASP/NINJA-PingU#2] opened 2014-02-05 01:39 UTC
I'm getting a segfault when running the examples:

```
bash-4.2# bin/npingu -t 3 -p 20-80 188.1.1.1-188.255.1.1 -d 1 -m Service
##################################################################
#          OWASP NINJA PingU Is Not Just A Ping Utility          #
##################################################################
Job Parameters:
    +Spotter Threads            [3]
    +Listener Threads           [1]
    +Enumerating services from port range   [20] to [80]
    +Start Scan Range           [188.1.1.1]
    +Stop Scan Range            [188.255.1.1]
    +Module                 [Service]
I found several potential local interfaces to use, please write the local ip to use:
```

I have a the loopback interface and wlan, so after specifying the wlan interface IP address. I tried other options and it's always throwing a segfault.

gdb is giving the following (after typing the IP address and pressing Enter):

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
##################################################################
#          OWASP NINJA PingU Is Not Just A Ping Utility          #
##################################################################
Job Parameters:
    +Spotter Threads            [3]
    +Listener Threads           [1]
    +Enumerating services from port range   [20] to [80]
    +Start Scan Range           [188.1.1.1]
    +Stop Scan Range            [188.255.1.1]
    +Module                 [Service]
I found several potential local interfaces to use, please write the local ip to use:
192.168.0.4
    +Local IP               [(null)]
##################################################################
Job Agents Creation:
[New Thread 0x7ffff75ee700 (LWP 3104)]
[New Thread 0x7ffff6ded700 (LWP 3105)]
[New Thread 0x7ffff65ec700 (LWP 3106)]
[New Thread 0x7ffff5deb700 (LWP 3107)]
[New Thread 0x7ffff53e2700 (LWP 3108)]
[New Thread 0x7ffff4be1700 (LWP 3109)]
    +Listener  Started at port [54321]
    +Spotter   Started at port [54321]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5deb700 (LWP 3107)]
0x00007ffff76f6c15 in inet_addr () from /lib64/libc.so.6
(gdb) quit
A debugging session is active.

    Inferior 1 [process 3100] will be killed.
```

I'm running Linux 3.10.17, Slackware, AMD Turion x86_64.

**Comment by guifre** [comment] 2014-02-05 09:17
Hello,

Thanks for reporting this. I have created a hotfix branch for this issue.

The problem is when trying to guess the interface to use. It would be very helpful if you could show me the output of # ifconfig

You can checkout https://github.com/OWASP/NINJA-PingU/archive/hotfix%232.zip it might already work

Regards.

**Comment by matiasinsaurralde** [comment] 2014-02-05 17:55
No problem, this is my ifconfig output:

```
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 16416  bytes 2295818 (2.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 16416  bytes 2295818 (2.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.12  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::924c:e5ff:fe1e:1783  prefixlen 64  scopeid 0x20<link>
        ether 90:4c:e5:1e:17:83  txqueuelen 1000  (Ethernet)
        RX packets 111980  bytes 34676092 (33.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 131042  bytes 51602267 (49.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by matiasinsaurralde** [comment] 2014-02-05 18:18
I checked the branch with the fix, it seems to be working now, thanks!

**Comment by guifre** [comment] 2014-02-05 18:57
Cool. I will close the issue then and merge the hotfix branch into master.

Thanks for reporting this, if you have any comment or feedback about the tool it will be appreciated.

Regards

**Closed as completed by guifre** 2014-02-05 18:57 UTC
